<div class="titulo">
    Login
</div>

<div class="login">
    <?php
    // within a view script
    $formLogin->prepare();
    // Assuming the "contact/process" route exists...
    $formLogin->setAttribute('action',$this->url('user/login',array('controller'=>'user','action'=>'login')));
    // Set the method attribute for the form
    $formLogin->setAttribute('method', 'post');

    // Get the form label plugin
    $formLabel = $this->plugin('formLabel');

    // Render the opening tag
    echo $this->form()->openTag($formLogin);
    ?>

    <table align="center">
        <tr>
    <?php
        $name = $formLogin->get('login');
        echo '<td>' . $name->getOption('label') . '</td><td>&nbsp;</td>';
        echo '<td>' . $this->formInput($name) . '</td>';
        echo $this->formElementErrors($name);
    ?>
        </tr>
        <tr>
    <?php
        $pass = $formLogin->get('senha');
        echo '<td>' . $pass->getOption('label') . '</td><td>&nbsp;</td>';
        echo '<td>' . $this->formInput($pass) . '</td>';
        echo $this->formElementErrors($pass);
    ?>
        </tr>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>        
        <tr>
            <td colspan="3">
                <div class="form_salvar">
                    <?php echo $this->formElement($formLogin->get('send')) ?>
                </div>
            </td>
        </tr>
    </table>


    <?php echo $this->form()->closeTag() ?>
</div>